<?php
// This file is part of Moodle - https://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <https://www.gnu.org/licenses/>.

/**
 * @author Daniel Poggenpohl
 * Date: 03.09.2024
 * @package local_coursetheme
 */

namespace local_coursetheme\ui;

defined('MOODLE_INTERNAL') || die;

use local_coursetheme\db\Theme_table;
use moodleform;

global $CFG;

require_once($CFG->libdir . '/formslib.php');

class edit_theme_form extends moodleform {
    function definition() {
        global $DB;
        $mform    = $this->_form;
        $themeid = $this->_customdata['id'];
        $mform->addElement('header', 'theme', 'Theme-Einstellungen');
        $mform->addElement('hidden', 'id');
        $mform->setType('id', PARAM_INT);
        $mform->addElement('text', 'name', 'Kurzname');
        $mform->setType('name', PARAM_TEXT);
        $mform->addElement('text', 'displayname', 'Anzeigename');
        $mform->setType('displayname', PARAM_TEXT);
        $mform->addElement('textarea', 'css', 'CSS-Regeln', ['rows' => 10]);
        $mform->setType('css', PARAM_TEXT);
        $mform->addElement('textarea', 'js', 'Javaskript', ['rows' => 10]);
        $mform->setType('js', PARAM_TEXT);
        $this->add_action_buttons();
        if ($themeid) {
            $theme = $DB->get_record(Theme_table::TABLE_NAME, ['id' => $themeid]);
            $this->set_data($theme);
        }
    }

    function definition_after_data() {
    }

    function validation($data, $files) {
        return parent::validation($data, $files); // TODO: Change the autogenerated stub
    }
}
