<?php
/**
 * Author: Daniel Poggenpohl
 * Date: 03.09.2024
 */

namespace local_coursetheme\ui;

defined('MOODLE_INTERNAL') || die;

use local_coursetheme\db\Theme_table;
use moodleform;

global $CFG;

require_once($CFG->libdir.'/formslib.php');

class edit_theme_form extends moodleform {

    function definition() {
        global $DB;
        $mform    = $this->_form;
        $themeId = $this->_customdata['id'];
        $mform->addElement('header','theme', 'Theme-Einstellungen');
        $mform->addElement('hidden', 'id');
        $mform->setType('id', PARAM_INT);
        $mform->addElement('text', 'name', 'Kurzname');
        $mform->setType('name', PARAM_TEXT);
        $mform->addElement('text', 'displayname', 'Anzeigename');
        $mform->setType('displayname', PARAM_TEXT);
        $mform->addElement('textarea', 'css', 'CSS-Regeln', ['rows' => 10]);
        $mform->setType('css', PARAM_TEXT);
        $mform->addElement('textarea', 'js', 'Javaskript', ['rows' => 10]);
        $mform->setType('js', PARAM_TEXT);
        $this->add_action_buttons();
        if ($themeId) {
            $theme = $DB->get_record(Theme_table::TABLE_NAME,['id' => $themeId]);
            $this->set_data($theme);
        }
    }

    function definition_after_data() {

    }

    function validation($data, $files) {
        return parent::validation($data, $files); // TODO: Change the autogenerated stub
    }
}
